JS Async Functions: API Status Challenge
neuefische/web-exercises pull request #104
Opened 2022-09-21 13:30 UTC by PReichetanz

rendered: https://github.com/neuefische/web-exercises/tree/feat/async-functions/api-status/sessions/js-async-functions/api-status

- [CSB](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/async-functions/api-status/sessions/js-async-functions/api-status?file=/README.md)

refers to neuefische/web-curriculum-new-format#20

2022-09-21 15:27 UTC, djfarly requested changes
this is not a full review 🫠

2022-09-21 15:27 UTC, djfarly commented on sessions/js-async-functions/api-status/js/index.js
> +});
```suggestion
// something needs to change here…
// ↙️
function checkIfApiIsAvailable() {
    /**
	 * Hint 1:
	 * Use the `fetch()` function and pass the `apiStatusUrl` into it
	 *
	 * Hint 2:
	 * The fetch function returns a promise which resolves to a Response
	 * object once it was received.
	 **/

	// --v-- write your code here --v--

	// --^-- write your code here --^--
}

button.addEventListener('click', () => {
	checkIfApiIsAvailable();
});
```

2022-09-21 15:27 UTC, djfarly commented on sessions/js-async-functions/api-status/js/index.js
> +const api = 'https://example-apis.vercel.app/api/status';
```suggestion
const apiStatusUrl = 'https://example-apis.vercel.app/api/status';
```

2022-09-22 10:32 UTC, CJAkkuec commented
Hey there, this was very fun - as per usual! :) Here's my (maybe a little whacky) [solution](https://codesandbox.io/s/crimson-river-wxfb0q?file=/js/index.js). No notes, all good imho.

2022-09-22 10:32 UTC, CJAkkuec approved these changes

2022-09-22 10:40 UTC, merged