React Basics: Hello World Challenge
neuefische/web-exercises pull request #127
Opened 2022-10-27 14:34 UTC by PReichetanz

rendered: https://github.com/neuefische/web-exercises/tree/react-basics-hello-world-challenge/sessions/react-basics/hello-world

## CSB

- [CSB](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-basics-hello-world-challenge/sessions/react-basics/hello-world?file=/README.md)

refers to neuefische/web-curriculum-new-format#190

2022-11-03 10:47 UTC, djfarly commented
ready for review :)

2022-11-04 11:12 UTC, CJAkkuec requested changes
LGTM 🚀 
[Here's my solution.](https://codesandbox.io/s/wizardly-wiles-6opti4?file=/src/App.js)

Just a couple of very minor notes. :)

2022-11-04 11:12 UTC, CJAkkuec commented on sessions/react-basics/hello-world/README.md
> +Render a heading with the text "Hello world!" to the browser. To do so, change the `div` into an `h1` and adapt its text accordingly.
```suggestion
Render a heading with the text "Hello world!" to the browser. To do so, change the `div` into an `h1` and change its text accordingly.
```

2022-11-04 11:12 UTC, CJAkkuec commented on sessions/react-basics/hello-world/README.md
> +- Look in the browser and marvel: nothing has changed, but you've just built and used your first React component!
```suggestion
- Look at the browser and be amazed: nothing has changed, but you've just built and used your first React component!
```

2022-11-07 09:59 UTC, merged