feat(feature/react-usestate-and-events): add exercise 02
neuefische/web-exercises pull request #15
Opened 2022-05-01 19:22 UTC by pixelass

migrated from
https://codesandbox.io/s/react-usestate-boolean-state-starter-wrmfgo

2022-05-02 13:34 UTC, PReichetanz submitted a review, later dismissed

2022-05-03 12:42 UTC, PReichetanz approved these changes
I think that this exercise works as expected.
[Please find my solution here](https://codesandbox.io/s/react-usestate-exercise-boolean-state-solution-tdlb4c?file=/App.js).

2022-05-11 13:36 UTC, F-Kirchhoff requested changes
LGTM, but there is an unneeded file that should be removed.

2022-05-11 14:10 UTC, PReichetanz commented on sessions/feature:react-usestate-and-events-exercise-02/src/createServiceWorker.js
> +}
I don't know! I guess we have to ask @pixelass about this.

2022-09-19 09:34 UTC, closed without merging