React Data Fetching: ISS Tracker
neuefische/web-exercises pull request #222
Opened 2022-12-09 13:10 UTC by PReichetanz

## `react-data-fetching/iss-tracker`

### 📄 [Rendered Exercise](https://github.com/neuefische/web-exercises/tree/react-data-fetching_iss/sessions/react-data-fetching/iss-tracker)

### 🔎 Review

Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-data-fetching_iss/sessions/react-data-fetching/iss-tracker?file=/README.md) or locally by running this command in your Terminal:

```
npx ghcd@latest neuefische/web-exercises/tree/react-data-fetching_iss/sessions/react-data-fetching/iss-tracker -i
```

### ✨ Copyable Markdown for Curriculum

````md
Solve this challenge on
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-data-fetching/iss-tracker?file=/README.md)
or locally by running this command in your Terminal:

```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-data-fetching/iss-tracker -i
```
````

refers to neuefische/web-curriculum-new-format#216

2022-12-12 10:55 UTC, aclaes requested changes
Good challenge! I have a few improvements ideas

2022-12-12 10:55 UTC, aclaes commented on sessions/react-data-fetching/iss-tracker/README.md
> +  - Note: `SWR` needs you to destructure a `data` object, but the `Map` and `Controls` component need a `coords` object passed to their props; how can you simply fix this naming issue without touchin
```suggestion
  - Note: `SWR` needs you to destructure a `data` object, but the `Map` and `Controls` component need `longitude` and `latitude` as separate props; how can you simply pass the coordinates from `data` without touching the props?
```

2022-12-12 13:36 UTC, PReichetanz commented on sessions/react-data-fetching/iss-tracker/README.md
> +  - Note: `SWR` needs you to destructure a `data` object, but the `Map` and `Controls` component need a `coords` object passed to their props; how can you simply fix this naming issue without touchin
We have found a good compromise.

2022-12-13 08:31 UTC, aclaes approved these changes
Very good, approve 🎉 Just two little improvements

2022-12-13 08:31 UTC, aclaes commented on sessions/react-data-fetching/iss-tracker/components/ISSTracker/index.js
> +        console.log(data);
```suggestion
```

2022-12-13 08:31 UTC, aclaes commented on sessions/react-data-fetching/iss-tracker/README.md
> +- Implement `SWR` to fetch the same data.
```suggestion
- Implement fetching of the same data with `SWR`.
```

2022-12-13 09:52 UTC, merged