React Data Fetching: Demo
neuefische/web-exercises pull request #225
Opened 2022-12-12 16:01 UTC by djfarly

tbd

2022-12-14 12:04 UTC, djfarly commented on sessions/react-data-fetching/demo-end/pages/_app.js
> +  );
yea thats better - i was just lazy

2022-12-16 12:54 UTC, PReichetanz requested changes
The demo works nicely as expected!

We just have to fix the readme.md files, then we are done.

2022-12-16 12:54 UTC, PReichetanz commented on sessions/react-data-fetching/demo-start/README.md
> +# React Data Fetching: Jokes
As we have already talked about, adapt the README.md files to the correct content of a demo.

2022-12-16 13:15 UTC, PReichetanz commented on sessions/react-data-fetching/demo-start/README.md
> +# React Data Fetching: Jokes
Update: adapted the readme files myself.

2022-12-16 13:19 UTC, PReichetanz approved these changes
I adapted the readme files myself, everything should be fine now.

@djfarly Just check the readme files again, that's it.

2022-12-19 09:08 UTC, djfarly commented on sessions/react-data-fetching/demo-end/components/Joke/index.js
> +          aria-label={isFunny ? "A Funny joke" : "Not a funny joke"}
```suggestion
          aria-label={isFunny ? "A laughing face" : "An unamused face"}
```

2022-12-19 09:49 UTC, merged