feat(js-fetch-and-asyncawait): add exercises
neuefische/web-exercises pull request #35
Opened 2022-06-15 13:05 UTC by anitaschiller

I converted both exercises to sandboxes, please review. In order to be able to commit the exercises, I had to deactivate some linting rules, e.g. that object properties have to be written in camelCase.

2022-08-04 15:01 UTC, macfrei requested changes
I really don't understand the color-clue assignments: https://codesandbox.io/s/color-clue-solution-22olbv?file=/js/index.js:665-675
I could not figure out what the goal of this exercise is and because of that I didn't know whether I did it right or wrong. Also, I changed a lot of the CSS and HTML as there were some unusual styling in place (e.g. styling main instead of body).

The star wars card app is a nice exercise to get used to fetch: https://codesandbox.io/s/star-wars-card-solution-sg775i?file=/js/index.js

2022-08-04 15:01 UTC, macfrei commented on sessions/js-fetch-and-asyncawait/star-wars-cards/index.html
> +	<script src="./js/index.js"></script>
```suggestion
		<link rel="stylesheet" href="./css/styles.css" />
		<script src="./js/index.js" defer></script>
	</head>
	<body>
		<main id="root"></main>
	</body>
```

2022-08-04 15:01 UTC, macfrei commented on sessions/js-fetch-and-asyncawait/star-wars-cards/js/index.js
> +		.then(); // ?
I would probably add a `catch` here as well.
```suggestion
	fetch() // ?
		.then() // ?
		.then() // ?
		.catch(); // ?
```

2022-08-15 14:31 UTC, ThomasKirst commented
> I agree, Lene, this exercise requires some time to figure out what the goal is and how it is supposed to work. It contains some 'noisy' computations that might raise questions that distract students from the real task – which is to implement a `fetch` call.

> I really don't understand the color-clue assignments: https://codesandbox.io/s/color-clue-solution-22olbv?file=/js/index.js:665-675
> I could not figure out what the goal of this exercise is and because of that I didn't know whether I did it right or wrong.

2022-09-19 09:35 UTC, closed without merging