Reintroduce unit testing demo and exercises
neuefische/web-exercises pull request #395
Opened 2024-08-27 08:11 UTC by onemanwenttomow

2024-08-28 09:18 UTC, NikRoe requested changes
Hi Pete,

thanks for the work you put into this!

I think the guide and exercise are looking fine.
However, I noticed that there are some files for codesandbox and some mentions in the README files on how to run the project in the codesandbox cloud. We should remove those files and mentions.

Thanks in advance 🙏

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/demo-end/.codesandbox/tasks.json
we should be able to remove this file safely, right?

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/demo-end/README.md
> +> The `npm run start` and `npm run test` scripts run automatically.
```suggestion
```

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/demo-start/.codesandbox/tasks.json
this file should be removable as well

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/demo-start/README.md
> +> The `npm run start` and `npm run test` scripts run automatically.
```suggestion
```

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/demo-start/sandbox.config.json
we should be able to remove this safely

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/demo-end/sandbox.config.json
we should be able to remove this safely

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/get-animal/.codesandbox/tasks.json
we should be able to remove this safely

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/get-animal/README.md
> +> The `npm run start` and `npm run test` scripts run automatically.
```suggestion
```

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/get-animal/sandbox.config.json
we should be able to remove this safely

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/math-functions/.codesandbox/tasks.json
we should be able to remove this safely

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/math-functions/README.md
> +> The `npm run start` and `npm run test` scripts run automatically.
```suggestion
```

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/math-functions/sandbox.config.json
we should be able to remove this safely

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/people/.codesandbox/tasks.json
we should be able to remove this safely

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/people/README.md
> +> The `npm run start` and `npm run test` scripts run automatically.
```suggestion
```

2024-08-28 09:18 UTC, NikRoe commented on sessions/js-unit-testing/people/sandbox.config.json
we should be able to remove this safely

2024-08-29 07:26 UTC, onemanwenttomow commented
> Hi Pete,
> 
> thanks for the work you put into this!
> 
> I think the most is looking fine. However, I noticed that there are some files for codesandbox and some mentions in the README files on how to run the project in the codesandbox cloud. We should remove those files and mentions.
> 
> Thanks in advance 🙏

Good points @NikRoe ! Thanks for the review

2024-08-29 07:35 UTC, NikRoe approved these changes
🥳

2024-08-29 07:58 UTC, merged